services:
  laravel:
    build:
      context: ./pdfLLMApp
      dockerfile: Dockerfile
    volumes:
      - ./pdfLLMApp:/var/www/laravel
      - laravel-storage:/var/www/laravel/storage/app/public
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:3Ms5zmf/nZ8mazGCJ+xemurlKi/gVflAK3II+bjpbpA=
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=pdfLLM
      - DB_USERNAME=pdfspear
      - DB_PASSWORD=Anubis-Sucks-1!234
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHON_HOST=python
    networks:
      - app-network

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - laravel-storage:/var/www/laravel/storage/app/public
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=pdfLLM
      - DB_USER=pdfspear
      - DB_PASSWORD=Anubis-Sucks-1!234
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_HOST=192.168.1.107
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - laravel-storage:/var/www/laravel/storage/app/public
    depends_on:
      - laravel
      - python
    networks:
      - app-network

  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: pdfLLM
      POSTGRES_USER: pdfspear
      POSTGRES_PASSWORD: Anubis-Sucks-1!234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: pdfllm@yourock.com
      PGADMIN_DEFAULT_PASSWORD: pdfLLMrox
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8087:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  laravel-storage:
  postgres-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge